---
title: Metadaten-Kataloge
lang: de
---
Die beschriebenen Datenstrukturen enthalten Metadaten. Für eine effiziente und konsistente Speicherung sind in den Aufgaben- bzw. Itemdaten jeweils nur Verweise gespeichert. Diese als `Key` hinterlegte Referenz lässt sich auflösen, wenn die entsprechenden Kataloge bzw. Wertelisten zur Verfügung stehen.

Diese sog. Metadatenkataloge stehen als JSON-Datei zum Download bereit. Für eine Orientierung sind sie außerdem in Textform einsehbar. Alle fächerspezifischen Variablen mit ihren Labels sowie den Werten, die sie annehmen können und diesen Value-Labels sind hier einsehbar:

* [VERA3 Mathematik](md-cat_V3MA.qmd) [{{< fa download >}}](md-cat_V3MA.yaml)
* [VERA3 Deutsch](md-cat_V3DE.qmd) [{{< fa download >}}](md-cat_V3DE.yaml)
* [VERA8 Mathematik](md-cat_V8MA.qmd) [{{< fa download >}}](md-cat_V8MA.yaml)
* [VERA8 Deutsch](md-cat_V8DE.qmd) [{{< fa download >}}](md-cat_V8DE.yaml)
* [VERA8 Englisch](md-cat_V8EN.qmd) [{{< fa download >}}](md-cat_V8EN.yaml)
* [VERA8 Französisch](md-cat_V8FR.qmd) [{{< fa download >}}](md-cat_V8FR.yaml)

In den Datenstrukturen sind weiterhin Konstanten in Aufzählungen verwendet. Diese sind übergreifende Key-Value-Paare und deren zugehörige Labels:

* [Fächerübergreifende Keys - Konstanten](constants.qmd) [{{< fa download >}}](constants.yaml)