---
title: "Daten"
lang: de
execute:
  echo: false
---

::: {.callout-important}
## Achtung: Nur Demo-Daten
Für die Jahre 2023 und 2024 sind Beispieldaten hinterlegt. Daten für den Durchgang 2025 werden hier nicht veröffentlicht.
:::

::: {.callout-note}

## Wählen Sie das Jahr

* [2024](2024)
* [2023](2023)

:::

# Download

Die Itemdaten werden als Download bereitgestellt. Klicken Sie hierzu im Kopf der jeweiligen Jahresdatei auf das Fach.

> Einige Browser starten dann nicht den Download, sondern wechseln zu einer Ansicht der Datei im Browser. Bei Firefox z. B. können Sie dann mit der Maus durch die Daten blättern. Wenn Sie jedoch wirklich die Datei erhalten wollen, kicken Sie mit der rechten Maustaste auf den Download-Link und wählen Sie 'Ziel speichern unter...'.

# Interaktiv

Außerdem können Sie auf den Jahresseiten interaktiv durch die Daten gehen, um sich einen ersten Eindruck zu verschaffen oder spezifische Werte nachzuschlagen. Dazu wählen Sie zuerst das Fach und dann ggf. ein Unterobjekt wie Aufgabe oder Item.

# Persistenz

Die Dateien mit den Itemwerten bleiben bis auf weiteres verfügbar. Die Links können also langfristig als Quelle verwendet werden.
